numpy is a scientific library that provides support for arrays, amtrices, along with collection of mathematical functions and operations on data structures

In [1]:
!pip install numpy

You should consider upgrading via the 'c:\users\aanan\appdata\local\programs\python\python39\python.exe -m pip install --upgrade pip' command.


In [2]:
import numpy as np

In [3]:
# Creating a 1 d array 
arr1d = np.array([1,2,3,4,5])
print(arr1d)

[1 2 3 4 5]


In [7]:
print(type(arr1d))
print(arr1d.shape)

<class 'numpy.ndarray'>
(5,)


In [10]:
arr2 = np.array([1,2,5,6,8,9,50,45,55])
arr2.reshape(1,9)

array([[ 1,  2,  5,  6,  8,  9, 50, 45, 55]])

In [14]:
arr2 = np.array([[1,2,5,6,8,9,50,45,55],[45,8,9,77,884,887,455,6454,55]])

In [15]:
print(arr2)

[[   1    2    5    6    8    9   50   45   55]
 [  45    8    9   77  884  887  455 6454   55]]


In [17]:
my_array = np.arange(0,10,2) #start,end,step
print(my_array)
my_array = my_array.reshape(5,1)
print(my_array)

[0 2 4 6 8]
[[0]
 [2]
 [4]
 [6]
 [8]]


In [19]:
two_d_unit_array = np.ones((3,4))
print(two_d_unit_array)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [21]:
# Creating an identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Numpy Vectorised Operation

In [22]:
arr1= np.array([1,2,3,4,5])
arr2= np.array([10,20,30,40,50])

print("Addition : ",arr1+arr2)
print("substraction : ",arr2-arr1)
print("Multiplication : ",arr2*arr1)
print("Multiplication : ",arr2/arr1)

Addition :  [11 22 33 44 55]
substraction :  [ 9 18 27 36 45]
Multiplication :  [ 10  40  90 160 250]
Multiplication :  [10. 10. 10. 10. 10.]


### Universal Function

In [25]:
arr = np.array([1,2,3,4,5])
print(np.sqrt(arr))

print(np.exp(arr))
print(np.sin(arr))
print(np.log(arr))

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [26]:
#Array slicing and indexing
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array : \n",arr)

Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [29]:
print(arr[1:,2:])

[[ 7  8]
 [11 12]]


In [32]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [33]:
arr[0][0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


### implimenting normalization , mean of 0 and standard deviation of 1

In [34]:
data = np.array([1,2,3,4,5])
mean= np.mean(data)
std_dev = np.stack(data)
normalized_data = (data-mean)/std_dev
print("Normalized Data : ",normalized_data)

Normalized Data :  [-2.   -0.5   0.    0.25  0.4 ]


In [35]:
data = np.array([1,2,3,4,5,6,7,8,9,10])
print("Mean : ",np.mean(data))
print("Median : ",np.median(data))
print("Standard Deviation : ",np.std(data))
print("Variance : ",np.var(data))


Mean :  5.5
Median :  5.5
Standard Deviation :  2.8722813232690143
Variance :  8.25


In [36]:
data>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [37]:
data[data>5]

array([ 6,  7,  8,  9, 10])

In [40]:
data[(data>=5) & (data<=10)]

array([ 5,  6,  7,  8,  9, 10])