numpy is a scientific library that provides support for arrays, amtrices, along with collection of mathematical functions and operations on data structures

In [1]:
!pip install numpy

You should consider upgrading via the 'c:\users\aanan\appdata\local\programs\python\python39\python.exe -m pip install --upgrade pip' command.


In [2]:
import numpy as np

In [3]:
# Creating a 1 d array 
arr1d = np.array([1,2,3,4,5])
print(arr1d)

[1 2 3 4 5]


In [7]:
print(type(arr1d))
print(arr1d.shape)

<class 'numpy.ndarray'>
(5,)


In [10]:
arr2 = np.array([1,2,5,6,8,9,50,45,55])
arr2.reshape(1,9)

array([[ 1,  2,  5,  6,  8,  9, 50, 45, 55]])

In [14]:
arr2 = np.array([[1,2,5,6,8,9,50,45,55],[45,8,9,77,884,887,455,6454,55]])

In [15]:
print(arr2)

[[   1    2    5    6    8    9   50   45   55]
 [  45    8    9   77  884  887  455 6454   55]]


In [17]:
my_array = np.arange(0,10,2) #start,end,step
print(my_array)
my_array = my_array.reshape(5,1)
print(my_array)

[0 2 4 6 8]
[[0]
 [2]
 [4]
 [6]
 [8]]


In [19]:
two_d_unit_array = np.ones((3,4))
print(two_d_unit_array)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [21]:
# Creating an identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])